services:
  - type: web
    name: mon-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    # Ajoutez vos autres variables d'environnement ici
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: ma-database
    #     property: connectionString
    
# Si vous avez une base de données, décommentez et configurez :
# databases:
#   - name: ma-database
#     databaseName: monapp
#     user: monuser
